# Generated by Django 4.2.4 on 2023-08-17 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=150)),
                ('Company_INN', models.IntegerField(default=0, verbose_name=25)),
                ('Company_Director', models.CharField(max_length=150)),
                ('Company_Place', models.CharField(max_length=32)),
                ('Company_Street', models.CharField(max_length=150)),
                ('Company_House_Number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flat_House_Address', models.TextField(blank=True, null=True)),
                ('Flat_Number', models.IntegerField(default=0, verbose_name=5)),
                ('Flat_Owner', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('House_Place', models.CharField(max_length=32)),
                ('House_Street', models.CharField(max_length=150)),
                ('House_Number', models.CharField(max_length=32)),
                ('House_Floor_Numbers', models.IntegerField(default=0, verbose_name=3)),
                ('House_Amount_Entrances', models.IntegerField(verbose_name=3)),
                ('House_Amount_Flats', models.IntegerField(default=0, verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit_Company', models.CharField(max_length=150)),
                ('Visit_Employee', models.CharField(max_length=150)),
                ('Visit_House', models.TextField(blank=True, null=True)),
                ('Visit_Reaction', models.CharField(max_length=25)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitFlat_Flat', models.IntegerField(default=0, verbose_name=5)),
                ('VisitFlat_Visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.visit')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserCompanies_Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.company')),
                ('UserCompanies_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlatContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlatContact_Name', models.CharField(max_length=150)),
                ('FlatContact_Phone', models.IntegerField(default=0, verbose_name=32)),
                ('FlatContact_Comment', models.TextField(blank=True, null=True)),
                ('Flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.flat')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='House',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.house'),
        ),
        migrations.CreateModel(
            name='CompaniesHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompaniesHouse_Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.company')),
                ('CompaniesHouse_House', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.house')),
            ],
        ),
    ]
