# Generated by Django 4.2.4 on 2023-08-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flat_Number', models.IntegerField(max_length=5)),
                ('Flat_Owner', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('House_Place', models.CharField(max_length=32)),
                ('House_Street', models.CharField(max_length=150)),
                ('House_Number', models.CharField(max_length=32)),
                ('House_Floor_Numbers', models.IntegerField(default=0, verbose_name=3)),
                ('House_Amount_Entrances', models.IntegerField(verbose_name=3)),
                ('House_Amount_Flats', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Flat_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flat_Contact_Name', models.CharField(max_length=150)),
                ('Flat_Contact_Phone', models.IntegerField(max_length=32)),
                ('Flat_Contact_Comment', models.TextField(blank=True, null=True)),
                ('Flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.flat')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='House',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.house'),
        ),
    ]
