# Generated by Django 4.2.4 on 2023-08-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='Flat_Number',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='flat_contact',
            name='Flat_Contact_Phone',
            field=models.IntegerField(verbose_name=32),
        ),
        migrations.AlterField(
            model_name='house',
            name='House_Amount_Flats',
            field=models.IntegerField(default=0, verbose_name=5),
        ),
    ]
