# Generated by Django 4.2.4 on 2023-08-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_flat_flat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Flat_House_Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
